### PR TITLE
Week-2: To Do List Project

### PR DESCRIPTION
**Pull request by faizi2500**
## This pull request contains the basic structure of the To-do app. ##

> We were asked to complete the following tasks for this PR
- [x] Set up a new project with webpack that is based on the webpack exercise you have already completed.
- [x] Create an index.html file and write your HTML markup here. Index.html file must be set as a template using the HTML Webpack Plugin. 
- [x] Create an index.js file and set an array of some simple to do tasks.
- [x]  Each task object should contain three keys:
1. description [string].
2. completed [bool].
3. index: [number]. 
- [x] On page load render the dynamically created list of tasks. 
- [x] Create a style.css and set rules for the To Do List. CSS must be loaded by Webpack Style/CSS Loader.

### CODE REVIEW

**Review by mimipeshy — CHANGES_REQUESTED** [review]
## Hi @faizi2500 👋🏾 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that I could not start. Kindly include a start script in your package.json.  Since this is a webpack project, I should see a script to start it. Also in your README file complete the instructions on how to set up your project locally.
Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._


Do not commit files that are not related to the project. Instead, add them to a .gitignore file. A common mistake is to commit enire node_modules directory which makes your pull request unreadable.

**Review by mimipeshy — CHANGES_REQUESTED** [review]
## Hi @faizi2500  👋🏾 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
#### Highlights

- items render dynamically on page load ✔️ 
- good GitHub workflow ✔️ 
- not forming any linter errors ✔️ 

## Required Changes ♻️

- [ ] To be able to use the  'serve' command you need to install: 'webpack-dev-server' package, Kindly include this package

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](<https://microverse.zendesk.com/hc/en-us/articles/1500004088561>) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](<https://airtable.com/shrQAqnBwek5a0O0s>)._

**Comment by faizi2500** [comment]
I followed this link to add webpack-dev-serve 
https://webpack.js.org/guides/development/#using-webpack-dev-server

When I run the command  my terminal shows  => 3 moderate severity vulnerabilities

**Review by mimipeshy — APPROVED** [review]
## Hi @faizi2500 👋🏾 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](<https://microverse.zendesk.com/hc/en-us/articles/1500004088561>)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](<https://airtable.com/shrQAqnBwek5a0O0s>)._

**Pull request merged**
